sudo: false

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2.8.0
  - ruby-head
  - jruby-head

before_install: gem install bundler

addons:
  postgresql: "9.6"

services:
  - postgresql

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
